name: Fetch tweets
on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5 - 3.8.5'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the app
        run: python app.py
        env:
          TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
          TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: push
        uses: actions-x/commit@v2
        with:
          name: GitHub Actions Autocommitter
          branch: main
          files: data/tweets2.csv
